#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)
timezone="$(timedatectl show --value --property=Timezone)"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep=".env storage/upload storage/export"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# UPDATE PHP DEPENDENCIES
#=================================================
ynh_script_progression "Updating PHP dependencies..."

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
